//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> phone_id { get; set; }
        public int quantity { get; set; }
        public decimal unit_price { get; set; }
        public decimal final_price { get; set; }
    
        public virtual order order { get; set; }
        public virtual phone phone { get; set; }
    }
}
