//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phone()
        {
            this.favorites = new HashSet<favorite>();
            this.order_details = new HashSet<order_details>();
            this.reviews = new HashSet<review>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> category_id { get; set; }
        public decimal price { get; set; }
        public Nullable<decimal> initial_price { get; set; }
        public Nullable<int> stock { get; set; }
        public string description { get; set; }
        public string image1 { get; set; }
        public string image2 { get; set; }
        public string image3 { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string chipset { get; set; }
        public string ram { get; set; }
        public string memory { get; set; }
        public string screen_size { get; set; }
        public string os { get; set; }
        public string camera { get; set; }
        public string pin { get; set; }
        public string resolution { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favorite> favorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<review> reviews { get; set; }
    }
}
